# Generated by Django 3.2.21 on 2024-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_alter_userprofile_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unique_code',
        ),
    ]
