# Generated by Django 3.2.21 on 2024-01-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_auto_20240129_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
