# Generated by Django 3.2.21 on 2024-01-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0008_alter_userprofile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recommended_by',
        ),
    ]
