# Generated by Django 3.2.21 on 2024-01-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0009_auto_20240129_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_by',
            field=models.ForeignKey(blank=True, help_text='The user who recommended this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended', to='investor.userprofile', verbose_name='recommended by'),
        ),
    ]
