# Generated by Django 3.2.21 on 2024-01-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_remove_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
