# Generated by Django 3.2.21 on 2024-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0014_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
