# Generated by Django 3.2.21 on 2024-02-05 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0015_alter_userprofile_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recommended_by',
            field=models.ForeignKey(blank=True, help_text='The user who recommended this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended', to=settings.AUTH_USER_MODEL, verbose_name='recommended by'),
        ),
    ]
