# Generated by Django 4.2.9 on 2024-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0020_remove_asset_date_useraccount_bonus_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='transactions_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
