# Generated by Django 4.2.9 on 2024-02-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0021_alter_useraccount_transactions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='transactions_id',
            field=models.CharField(max_length=12),
        ),
    ]
