# Generated by Django 4.2.9 on 2024-02-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0022_alter_useraccount_transactions_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_id', models.CharField(default=True, max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_ids', to='investor.userprofile')),
            ],
        ),
    ]
