# Generated by Django 4.2.9 on 2024-02-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0023_transaction_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_ids',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Asset', to='investor.userprofile'),
        ),
        migrations.AlterField(
            model_name='transaction_ids',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_ids', to='investor.userprofile'),
        ),
    ]
