# Generated by Django 4.2.9 on 2024-02-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0024_transaction_ids_balance_alter_asset_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_ids',
            name='balance',
        ),
    ]
