# Generated by Django 4.2.9 on 2024-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0025_remove_transaction_ids_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_ids',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
