# Generated by Django 4.2.9 on 2024-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0026_transaction_ids_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_ids',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction_ids',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
