# Generated by Django 4.2.9 on 2024-02-26 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0030_remove_transaction_ids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_ids',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_ids', to='investor.userprofile'),
            preserve_default=False,
        ),
    ]
