# Generated by Django 4.2.9 on 2024-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0034_alter_transaction_ids_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_ids',
            name='transactions_id',
            field=models.CharField(max_length=12),
        ),
    ]
