# Generated by Django 4.2.9 on 2024-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0035_alter_transaction_ids_transactions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_ids',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
