# Generated by Django 4.2.9 on 2024-02-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0037_alter_transaction_ids_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_ids',
            name='user',
        ),
    ]
