# Generated by Django 4.2.9 on 2024-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0038_remove_transaction_ids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_ids',
            name='user',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
