# Generated by Django 4.2.9 on 2024-03-01 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0050_alter_deposit_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Deposit', to=settings.AUTH_USER_MODEL),
        ),
    ]
