# Generated by Django 4.2.9 on 2024-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0053_alter_deposit_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
