# Generated by Django 4.2.10 on 2024-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0056_amountwithdrawn_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('phone_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AmountWithdrawn',
        ),
    ]
