# Generated by Django 4.2.10 on 2024-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0058_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
