# Generated by Django 4.2.10 on 2024-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0061_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
