# Generated by Django 4.2.10 on 2024-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0062_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
