# Generated by Django 4.2.10 on 2024-03-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0064_purchase_description_purchase_image_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
