# Generated by Django 4.2.10 on 2024-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0065_alter_purchase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
