# Generated by Django 4.2.10 on 2024-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0066_alter_userprofile_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
