# Generated by Django 4.2.10 on 2024-03-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0067_alter_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='confirmation_name',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
