# Generated by Django 4.2.10 on 2024-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0068_withdrawalrequest_confirmation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
