# Generated by Django 4.2.10 on 2024-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0070_remove_useraccount_name_deposit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_ids',
            name='name',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
