# Generated by Django 4.2.10 on 2024-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0071_transaction_ids_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='name',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
