# Generated by Django 4.2.10 on 2024-03-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0072_withdrawal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
