# Generated by Django 4.2.10 on 2024-04-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0073_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=12),
        ),
    ]
