# Generated by Django 4.2.9 on 2024-07-04 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0076_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
